// Mocks generated by Mockito 5.4.6 from annotations
// in spoolscan/test/services/spool_resolver_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:http/http.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:spoolscan/models/spool.dart' as _i3;
import 'package:spoolscan/services/spoolman_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeClient_0 extends _i1.SmartFake implements _i2.Client {
  _FakeClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSpool_1 extends _i1.SmartFake implements _i3.Spool {
  _FakeSpool_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SpoolmanService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSpoolmanService extends _i1.Mock implements _i4.SpoolmanService {
  MockSpoolmanService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Client get client =>
      (super.noSuchMethod(
            Invocation.getter(#client),
            returnValue: _FakeClient_0(this, Invocation.getter(#client)),
          )
          as _i2.Client);

  @override
  _i5.Future<_i3.Spool> fetchSpool(String? baseUrl, String? spoolId) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSpool, [baseUrl, spoolId]),
            returnValue: _i5.Future<_i3.Spool>.value(
              _FakeSpool_1(
                this,
                Invocation.method(#fetchSpool, [baseUrl, spoolId]),
              ),
            ),
          )
          as _i5.Future<_i3.Spool>);

  @override
  _i5.Future<List<_i3.Spool>> listSpools(String? baseUrl) =>
      (super.noSuchMethod(
            Invocation.method(#listSpools, [baseUrl]),
            returnValue: _i5.Future<List<_i3.Spool>>.value(<_i3.Spool>[]),
          )
          as _i5.Future<List<_i3.Spool>>);

  @override
  _i5.Future<int> createVendor(String? baseUrl, {required String? name}) =>
      (super.noSuchMethod(
            Invocation.method(#createVendor, [baseUrl], {#name: name}),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<int> createFilament(
    String? baseUrl, {
    required int? vendorId,
    required String? name,
    required String? material,
    required String? colorHex,
    int? extruderTemp,
    double? diameter = 1.75,
    double? density = 1.24,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createFilament,
              [baseUrl],
              {
                #vendorId: vendorId,
                #name: name,
                #material: material,
                #colorHex: colorHex,
                #extruderTemp: extruderTemp,
                #diameter: diameter,
                #density: density,
              },
            ),
            returnValue: _i5.Future<int>.value(0),
          )
          as _i5.Future<int>);

  @override
  _i5.Future<_i3.Spool> createSpool(
    String? baseUrl, {
    required int? filamentId,
    int? initialWeight,
    Map<String, String>? extra,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #createSpool,
              [baseUrl],
              {
                #filamentId: filamentId,
                #initialWeight: initialWeight,
                #extra: extra,
              },
            ),
            returnValue: _i5.Future<_i3.Spool>.value(
              _FakeSpool_1(
                this,
                Invocation.method(
                  #createSpool,
                  [baseUrl],
                  {
                    #filamentId: filamentId,
                    #initialWeight: initialWeight,
                    #extra: extra,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i3.Spool>);

  @override
  _i5.Future<void> patchSpoolExtra(
    String? baseUrl,
    String? spoolId,
    Map<String, String>? extra,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#patchSpoolExtra, [baseUrl, spoolId, extra]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<List<_i4.SpoolmanVendor>> listVendors(String? baseUrl) =>
      (super.noSuchMethod(
            Invocation.method(#listVendors, [baseUrl]),
            returnValue: _i5.Future<List<_i4.SpoolmanVendor>>.value(
              <_i4.SpoolmanVendor>[],
            ),
          )
          as _i5.Future<List<_i4.SpoolmanVendor>>);

  @override
  _i5.Future<List<_i4.SpoolmanFilament>> listFilaments(
    String? baseUrl, {
    int? vendorId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#listFilaments, [baseUrl], {#vendorId: vendorId}),
            returnValue: _i5.Future<List<_i4.SpoolmanFilament>>.value(
              <_i4.SpoolmanFilament>[],
            ),
          )
          as _i5.Future<List<_i4.SpoolmanFilament>>);
}
